#!/usr/bin/env bash

update_bluetooth_service()
{
    local target="$1"

    local -a lines=(
        "ExecStart=/usr/lib/bluetooth/bluetoothd -C\n"
        "ExecStartPost=/usr/bin/sdptool add SP\n"
        "ExecStartPost=/bin/hciconfig hci0 piscan"
    )

    if [ $( grep "${lines[1]}" "$target" ) ]; then
        echo "...lines already included."
        return 1
    else
        local IFS=$''
        sed -i s%^Exec.*$%"${lines[*]}"%g "$target"
    fi
}


create_rfcomm_service()
{
    local target="$1"

    local IFS=$'\n'
    local -a lines=(
        "[Unit]"
        "Description=RFCOMM service"
        "After=bluetooth.service"
        "Requires=bluetooth.service"
        ""
        "[Service]"
        "ExecStart=/usr/bin/rfcomm watch hci0 1 getty rfcomm0 115200 vt100 -a pi"
        ""
        "[Install]"
        "WantedBy=multi-user.target"
    )

    if [ -e "$target" ]; then
        echo -n "rfcomm already exists"
        if [ $( grep "${lines[1]}" "$target" ) ]; then
            echo "...lines already included."
            return 1
        fi
    fi

    echo "${lines[*]}" > "$target"

    cp rfcomm.conf "$targetbase/etc/bluetooth"
}


#########################
# Execution Begins Here #
#########################

declare targetbase="mpoint"   # for rootfs mounted on another computer
# declare targetbase=""         # for rootfs mounted on the RPi computer


declare targetroot="$targetbase/lib/systemd/system"

update_bluetooth_service "$targetroot/bluetooth.service"
create_rfcomm_service "$targetroot/rfcomm.service"
