#!/usr/bin/env bash

is_root() { [ "$USER" == "root" ]; }

download_build_install_valgrind()
{
    wget https://sourceware.org/pub/valgrind/valgrind-3.17.0.tar.bz2
    tar -xf valgrind-3.27.0.tar.bz2
    cd valgrind-3.27.0
    ./configure
    make
    chown pi:pi -R ../../valgrind-3.27.0
    make install
    cd ..
}

if is_root; then
    apt-get update
    apt-get install -y git emacs-nox texinfo

    ./lamp_setup

    # Preprequisite for building SchemaServer
    apt-get install -y libfcgi-dev
    # Prerequisite for packaging the framework
    apt-get install -y uglifyjs

    declare OPWD="${PWD}"
    cd /home/pi
    mkdir www src
    cd src

    # valgrind is considered deficient, look-up and use -fsanitize=address
    # download_build_install_valgrind

    git clone https://github.com/cjungmann/SchemaServer.git
    git clone https://github.com/cjungmann/schemafw.git

    cd ..

    chown -R pi:pi src
    chown -R pi:pi www


    cd "${OPWD}"
else
    echo "You must be root to run this script (use \"sudo\")."
fi
