#!/usr/bin/env bash

is_root() { [ "$USER" == "root" ]; }

download_build_install_valgrind()
{
    wget https://sourceware.org/pub/valgrind/valgrind-3.17.0.tar.bz2
    tar -xf valgrind-3.27.0.tar.bz2
    cd valgrind-3.27.0
    ./configure
    make
    make install
}

if is_root; then
    apt-get update
    apt-get install -y git emacs-nox texinfo

    ./lamp_setup

    # Preprequisite for building SchemaServer
    apt-get install -y libfcgi-dev
    # Prerequisite for packaging the framework
    apt-get install -y uglifyjs

    download_build_install_valgrind

    declare OPWD="${PWD}"
    cd /home/pi
    mkdir www src
    cd src
    git clone https://github.com/cjungmann/SchemaServer.git
    git clone https://github.com/cjungmann/schemafw.git

    chown -R pi:pi SchemaServer
    chown -R pi:pi schemafw


    cd "${OPWD}"
else
    echo "You must be root to run this script (use \"sudo\")."
fi
