#!/usr/bin/env bash

is_root() { [ "$USER" == "root" ]; }

if is_root; then
    apt-get update
    apt-get install -y git emacs-nox
else
    echo "You must be root to run this script (use \"sudo\")."
fi
