#!/usr/bin/env bash

declare C_GREEN="[32;1m"

is_root() { [ "$USER" == "root" ]; }

# Waits for and returns single keypress, even if it is
# represented by multiple characters.
get_keypress()
{
    # IFS characters will be invisible to 'read', so:
    local IFS=''

    # Array to collect chars in case of multi-char keypress
    local -a chars=( )
    
    # Wait for a keypress (-n 1), save to array
    local keychar
    read -n 1 -s keychar
    chars=( "$keychar" )

    # Collect additional characters if available, especially for escape characters
    while read -t 0; do
        read -n 1 keychar
        chars=( "${chars[@]}" "$keychar" )
    done

    # empty IFS so array is joined without delimiters
    echo "${chars[*]}"
}


install_apache()
{
    echo "${C_GREEN}Installing apache[m"
    apt-get install -y apache2-bin
    ufw allow in "Apache"
}

set_mariadb_root_password()
{
    local pword1=1 pword2=2 respkey
    until [ "${pword1}" == "${pword2}" ]; do
        pword1=""
        pword2=""
        echo -n "Enter a MySQL root password "
        read -s pword1
        echo
        echo -n "Reenter the password "
        read -s pword2
        echo

        if [ "${pword1}" ] && [ "${pword1}" != "${pword2}" ]; then
            echo "The passwords do not match."
            echo -n "Press ENTER to try again, \"S\" to skip setting the password."
            while [ 1 -eq 1 ]; do
                respkey=$( get_keypress )
                if [ "${#respkey}" -eq 0 ]; then
                    break;
                elif [ "${respkey}" == "s" ] || [ "${respkey}" == "S" ]; then
                    pword1="${pword2}"
                    break
                fi
            done
            echo
        else
            echo "Detected matching passwords, setting root password now."
            local query="ALTER USER 'root'@'localhost' IDENTIFIED BY '${pword1}'"
            mysql -uroot -e "${query}"
        fi
    done
}

install_mariadb()
{
    echo "${C_GREEN}Installing maria db[m"
    apt-get install -y mariadb-server libmariadb-dev
    cp -s /usr/bin/mariadb_config /usr/bin/mysql_config
    ln -s /usr/include/mariadb /usr/include/mysql

    echo "${C_GREEN}Login with 'root' with 'sudo mysql -u root'[m"
    echo "${C_GREEN}You will have to create regular users.[m"
    echo "${C_GREEN}You may want to create a default user in .my.cnf.[m"
}

install_www-data()
{
    echo "Creating www-data user without a password."

    sudo mysql -e "CREATE USER 'www-data'@'localhost'";

    echo "Adding privileges to www-data."
    local -a PRIVS=(
        CREATE
        DELETE
        INSERT
        SELECT
        UPDATE
        DROP
        )

    IFS=','
    sudo mysql -e "GRANT ${PRIVS[@]} ON *.* TO 'www-data'@'localhost'"
    }

install_php()
{
    echo "${C_GREEN}Installing php[m"
    apt-get install -y php libapache2-mod-php php-mysql
}

install_fastcgi()
{
    echo "${C_GREEN}Installing FastCGI[m"
    apt-get install -y libfcgi-dev
}

install_texinfo()
{
    echo "${C_GREEN}Installing texinfo utilities, including makeinfo[m"
    apt-get install -y texinfo
}

install_git()
{
    echo "${C_GREEN}Installing git environment[m"
    apt-get install -y git
}

if ! is_root; then 
    echo "You must be root to run this script."
else
    sudo apt-get update -y
    sudo apt-get upgrade -y
 
    if ! which apache2; then
        install_apache
    fi
    
    if ! which mysql; then
        install_mariadb
        install_www-data
        set_mariadb_root_password
    fi

    if ! which php; then
        install_php
    fi

    if ! which makeinfo; then
        install_texinfo
    fi

    if ! which git; then
        install_git
    fi
       
fi
