#!/bin/sh

is_root() { [ "$USER" == "root" ]; }
export ASSUME_ALWAYS_YES=yes;

##################
#      Main      #
##################

if ! is_root; then
    echo "You must be root to run this script."
    exit 1
fi

echo "BASH is better for some scripting stuff (IMHO), so"
echo "this script installs BASH then runs another script that"
echo "uses BASH features for a more interactive script."
echo
echo "We start with getting a username and password for"
echo "a sudo user, then the rest should run unattended."
echo


if type pkg 2>1 1>/dev/null; then
    pkg bootstrap
    if ! type bash 2>1 1>/dev/null; then
        pkg install bash
        if [ $? -ne 0 ]; then
            echo "Failed to install bash.  Can't proceed, aborting."
            exit 1
        fi
    fi

    bash ./bsd_setup_continued
else
    echo "Can't find 'pkg' package manager, suspect non-BSD system.  Aborting."
fi
