#!/usr/bin/env bash

declare DONE="[32;1m"   ## set foregound to green
declare FAIL="[31;1m"   ## set foreground to red
declare NONEED="[34;1m" ## set blue foreground
declare COFF="[m"       ## return to default foreground color

export ASSUME_ALWAYS_YES=yes;

is_root() { [ "$USER" == "root" ]; }

get_yes_no()
{
    local keyp
    while true; do
        read -n1 -p"[Y]es or [N]o: " keyp
        if [ $? -eq 0 ]; then
            if [ "${keyp^^}" == "Y" ]; then
                echo
                return 0
            elif [ "${keyp^^}" == "N" ]; then
                echo
                return 1
            else
                echo -n "[2K[1G"  # erase line; move to leftmost (1) column
            fi
        fi
    done
}

