#!/usr/bin/env bash

is_root() { [ "$USER" == "root" ]; }

declare DONE="[32;1m"   ## set foregound to green
declare FAIL="[31;1m"   ## set foreground to red
declare NONEED="[34;1m" ## set blue foreground
declare COFF="[m"       ## return to default foreground color

declare SUSER=
declare SPASS=

export ASSUME_ALWAYS_YES=yes;

get_yes_no()
{
    local keyp
    while true; do
        read -n1 -p"[Y]es or [N]o: " keyp
        if [ $? -eq 0 ]; then
            if [ "${keyp^^}" == "Y" ]; then
                echo
                return 0
            elif [ "${keyp^^}" == "N" ]; then
                echo
                return 1
            else
                echo -n "[2K[1G"  # erase line; move to leftmost (1) column
            fi
        fi
    done
}

get_name_and_password()
{
    local -n suser=SUSER
    local -n spass=SPASS

    echo -n "Enter a new sudo user: "
    read suser
    echo
    while true; do
        echo -n "Enter a password for '${suser}': "
        read -s spass1
        if [ $? -ne 0 ]; then
            echo
        else
            echo
            echo -n "Reenter the password: "
            read -s spass
            if [ $? -eq 0 ]; then
                if [ "$spass" == "$spass1" ]; then
                    echo
                    return 0
                else
                    spass=
                    spass1=
                    echo
                    echo "Password mismatch: try again."
                fi
            fi
        fi
    done

    return 1
}

check_sudoers()
{
    local user="$1"
    local -i found=1
    grep -qs "${user}" /usr/local/etc/sudoers
    found=$?
    if [ $found -ne 0 ]; then
        grep -qs "${user}" /usr/local/etc/sudoers.d/*
        found=$?
    fi

    return $found
}

update_sudoers()
{
    local user="$1"

    if ! which sudo 2>/dev/null; then
        pkg -y install sudo
        if [ $? -eq 0 ]; then
            echo "${DONE}Sudo installed.${COFF}"
        else
            echo "${FAIL}Sudo not installed.${COFF}"
            exit 1
        fi
    fi

    if ! check_sudoers "${user}"; then
        echo "${user} ALL=(ALL) ALL" > /usr/local/etc/sudoers.d/"${user}"
        echo "${DONE}Added '${user}' as sudo user.${COFF}"
        service sudo restart
        if [ $? -eq 0 ]; then
            echo "${DONE}Restarted sudo.${COFF}"
        else
            echo "${FAIL}Failed to restart sudo.${COFF}"
        fi
    fi
}

add_sudo_user()
{
    local user="$1"
    local pword="$2"
    echo "${pword}" | pw add user "${user}" -m -h 0
    if [ $? -eq 0 ]; then
        echo "${DONE}Added user ${user} to this system.${COFF}"
        update_sudoers "${user}"
    else
        echo "${FAIL}Failed to add user ${user}.${COFF}"
    fi
}


##################
#      Main      #
##################

echo "Create a sudo user right now?"
if get_yes_no; then
    if is_root; then
        if get_name_and_password; then
            add_sudo_user "${SUSER}" "${SPASS}"
        fi
    else
        echo "You must be root to run this script."
        exit 1
    fi
fi
